[[inputs.mqtt_consumer]]
    servers = ["tcp://eclipse-mosquitto:1883"]
    topics = ["sensors"]
        data_format = "influx"
        influx_timestamp_precision="1s"
[[outputs.influxdb_v3]]
    urls = ["http://influxdb:8181"]
    token = "apiv3_QJWo-CMr1SZaCtpMrCV8BvI6Ix_B72o53aT-fWDffT9KkH7gdIn09y9NtNKrI3rsRhHyFJzKYQL3kVVoGsLAsQ"
    database = "sensors"
    precision = "1s"
