services:
  # DATABASE REDIS
  redis:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"
     
  # SCRIPT PYTHON PER SENSORE
  sensor-script:
    image: mattiaanastasi/sensors-pi
    container_name: python-sensor-app
    depends_on:
      - redis 
    privileged: true
    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MQTT_PORT=1883
      - MQTT_IP=192.168.1.238
      - DHT_PIN_NUMBER=10
      - HC_SR04_TRIG_NUMBER=22
      - HC_SR04_ECHO_NUMBER=23